# pull official--image
FROM node:12.16.0-alpine

# set work directory
WORKDIR /masjid-app

# add `/masjid-app/node_modules/.bin` to $PATH
ENV PATH /masjid-app/node_modules/.bin:$PATH

# install dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install


# add app
COPY . ./

# start app
CMD ["yarn", "start"]
