version: '3.7'

services:

  masjid-app:
    container_name: masjid-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/masjid-app'
      - '/masjid-app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true